# Generated by Django 2.2.3 on 2019-07-24 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Children',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=20, verbose_name='学号')),
                ('nick_name', models.CharField(default='', max_length=10, verbose_name='姓名')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='生日')),
                ('gender', models.CharField(choices=[('male', '男'), ('female', '女')], default='female', max_length=6, verbose_name='性别')),
                ('address', models.CharField(default='', max_length=100, verbose_name='地址')),
                ('mobile', models.CharField(blank=True, max_length=11, null=True, verbose_name='手机号')),
                ('image', models.ImageField(default='image?default.png', upload_to='image/%Y/%m', verbose_name='头像')),
            ],
            options={
                'verbose_name': '幼儿信息',
                'verbose_name_plural': '幼儿信息',
            },
        ),
    ]
