# Generated by Django 2.2.3 on 2019-07-25 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=20, verbose_name='学号')),
                ('nick_name', models.CharField(default='', max_length=10, verbose_name='姓名')),
                ('birthday', models.DateField(verbose_name='生日')),
                ('gender', models.CharField(choices=[('male', '男'), ('female', '女')], default='female', max_length=6, verbose_name='性别')),
                ('age', models.IntegerField(default=0, verbose_name='年龄')),
                ('address', models.CharField(default='', max_length=100, verbose_name='地址')),
                ('mobile', models.CharField(max_length=11, verbose_name='手机号')),
                ('image', models.ImageField(default='image?default.png', upload_to='image/%Y/%m', verbose_name='头像')),
            ],
            options={
                'verbose_name': '幼儿信息',
                'verbose_name_plural': '幼儿信息',
            },
        ),
        migrations.CreateModel(
            name='ClassInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_id', models.CharField(default='', max_length=10, verbose_name='园区号')),
                ('school_name', models.CharField(default='', max_length=10, verbose_name='园区名称')),
                ('class_name', models.DateField(choices=[('xxb', '小小班'), ('xb', '小班'), ('zb', '中班'), ('db', '大班')], max_length=3, verbose_name='班级')),
                ('address', models.CharField(default='', max_length=100, verbose_name='地址')),
                ('main_teacher', models.CharField(default='', max_length=20, verbose_name='班主任')),
                ('mobile', models.CharField(blank=True, max_length=11, null=True, verbose_name='手机号')),
                ('child_number', models.IntegerField(default=0, verbose_name='班级人数')),
            ],
            options={
                'verbose_name': '班级信息',
                'verbose_name_plural': '班级信息',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=20, verbose_name='工号')),
                ('nick_name', models.CharField(default='', max_length=10, verbose_name='姓名')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='年龄')),
                ('gender', models.CharField(choices=[('male', '男'), ('female', '女')], default='female', max_length=6, verbose_name='性别')),
                ('class_info', models.CharField(default='', max_length=15, verbose_name='班级')),
                ('position', models.CharField(default='', max_length=20, verbose_name='职务')),
                ('work_years', models.IntegerField(default=0, verbose_name='工作年限')),
                ('points', models.CharField(default='', max_length=50, verbose_name='教学特点')),
                ('mobile', models.CharField(blank=True, max_length=11, verbose_name='手机号')),
                ('email', models.CharField(blank=True, max_length=50, null=True, verbose_name='邮箱')),
            ],
            options={
                'verbose_name': '教师信息',
                'verbose_name_plural': '教师信息',
            },
        ),
    ]
